//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StronglyTyped.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StronglyTyped.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable restore.
        /// </summary>
        internal static string AutoGeneratedFooter {
            get {
                return ResourceManager.GetString("AutoGeneratedFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by the StronglyTyped source generator
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///#nullable enable.
        /// </summary>
        internal static string AutoGeneratedHeader {
            get {
                return ResourceManager.GetString("AutoGeneratedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StronglyTyped.
        /// </summary>
        internal static string NamespaceForStronglyTypedLibrary {
            get {
                return ResourceManager.GetString("NamespaceForStronglyTypedLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX.
        /// </summary>
        internal static string PlaceholderForTypesInTemplate {
            get {
                return ResourceManager.GetString("PlaceholderForTypesInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongBool&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Boolean Value { get; init; }
        ///
        ///    private static readonly ZYX _true = new(true);
        ///    public static ZYX True =&gt; _true;
        ///
        ///    private static readonly ZYX _false = new(false);
        ///    public static ZYX False =&gt; _false;
        ///
        ///    public bool IsTru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongBoolTemplate {
            get {
                return ResourceManager.GetString("StrongBoolTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongByte&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Byte Value { get; init; }
        ///
        ///    private readonly static ZYX _one = new((byte)1);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static ZYX _zero = new((byte)0);
        ///    public static ZYX Zero =&gt; _zero;
        ///
        ///    [global::System.Diagnostics.Contracts. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongByteTemplate {
            get {
                return ResourceManager.GetString("StrongByteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongDecimal&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Decimal Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new(-1m);
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new(1m);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongDecimalTemplate {
            get {
                return ResourceManager.GetString("StrongDecimalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongDouble&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Double Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new(-1d);
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new(1d);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly stati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongDoubleTemplate {
            get {
                return ResourceManager.GetString("StrongDoubleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongFloat&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Single Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new(-1f);
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new(1f);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongFloatTemplate {
            get {
                return ResourceManager.GetString("StrongFloatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StronglyTyped.StrongGuidAttribute.
        /// </summary>
        internal static string StrongGuidAttribute {
            get {
                return ResourceManager.GetString("StrongGuidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///[global::System.Text.Json.Serialization.JsonConverter(typeof(SystemJsonConverter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongGuid&lt;ZYX&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// The Guid value this ZYX contains
        ///    /// &lt;/summary&gt;
        ///    public required global::System.Guid Value { get; init; }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Creates a new ZYX from a newly generated Guid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongGuidTemplate {
            get {
                return ResourceManager.GetString("StrongGuidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongHalf&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Half Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new((global::System.Half)(-1));
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new((global::System.Half)1);
        ///    public static ZYX One  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongHalfTemplate {
            get {
                return ResourceManager.GetString("StrongHalfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongInt&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Int32 Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new(-1);
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new(1);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static ZYX  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongIntTemplate {
            get {
                return ResourceManager.GetString("StrongIntTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongLong&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Int64 Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new(-1L);
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new(1L);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static Z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongLongTemplate {
            get {
                return ResourceManager.GetString("StrongLongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongSByte&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.SByte Value { get; init; }
        ///
        ///    private readonly static ZYX _negativeOne = new((global::System.SByte)(-1));
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private readonly static ZYX _one = new((global::System.SByte)1);
        ///    public static ZYX  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongSByteTemplate {
            get {
                return ResourceManager.GetString("StrongSByteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongShort&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.Int16 Value { get; init; }
        ///
        ///    private static readonly ZYX _negativeOne = new((global::System.Int16)(-1));
        ///    public static ZYX NegativeOne =&gt; _negativeOne;
        ///
        ///    private static readonly ZYX _one = new((global::System.Int16)1);
        ///    public static ZYX  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongShortTemplate {
            get {
                return ResourceManager.GetString("StrongShortTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongString&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.String Value { get; init; }
        ///
        ///    private static readonly ZYX _empty = new(global::System.String.Empty);
        ///    public static ZYX Empty =&gt; _empty;
        ///
        ///    [global::System.Diagnostics.Contracts.Pure]
        ///    public static explicit operator global::System.String( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongStringTemplate {
            get {
                return ResourceManager.GetString("StrongStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongUInt&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.UInt32 Value { get; init; }
        ///
        ///    private readonly static ZYX _one = new((global::System.UInt32)1);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static ZYX _zero = new((global::System.UInt32)0);
        ///    public static ZYX Zero =&gt; _zero;
        ///
        ///    [g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongUIntTemplate {
            get {
                return ResourceManager.GetString("StrongUIntTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongULong&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.UInt64 Value { get; init; }
        ///
        ///    private readonly static ZYX _one = new((global::System.UInt64)1);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static ZYX _zero = new((global::System.UInt64)0);
        ///    public static ZYX Zero =&gt; _zero;
        ///
        ///    [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongULongTemplate {
            get {
                return ResourceManager.GetString("StrongULongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentModel.TypeConverter(typeof(Converter))]
        ///public readonly partial record struct ZYX : global::StronglyTyped.IStrongUShort&lt;ZYX&gt;
        ///{
        ///    public required readonly global::System.UInt16 Value { get; init; }
        ///
        ///    private readonly static ZYX _one = new((global::System.UInt16)1);
        ///    public static ZYX One =&gt; _one;
        ///
        ///    private readonly static ZYX _zero = new((global::System.UInt16)0);
        ///    public static ZYX Zero =&gt; _zero;
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrongUShortTemplate {
            get {
                return ResourceManager.GetString("StrongUShortTemplate", resourceCulture);
            }
        }
    }
}
