//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrictlyTyped.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrictlyTyped.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable restore.
        /// </summary>
        internal static string AutoGeneratedFooter {
            get {
                return ResourceManager.GetString("AutoGeneratedFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by the StronglyTyped source generator
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///#nullable enable.
        /// </summary>
        internal static string AutoGeneratedHeader {
            get {
                return ResourceManager.GetString("AutoGeneratedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StronglyTyped.
        /// </summary>
        internal static string NamespaceForStronglyTypedLibrary {
            get {
                return ResourceManager.GetString("NamespaceForStronglyTypedLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXX.
        /// </summary>
        internal static string PlaceholderForTypesInTemplate {
            get {
                return ResourceManager.GetString("PlaceholderForTypesInTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a strictly-typed record struct for a boolean value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictBool{T}&quot;/&gt; interface
        ////// for strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictBoolTemplate {
            get {
                return ResourceManager.GetString("StrictBoolTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed struct for a unsigned byte value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictByte{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictByteTemplate {
            get {
                return ResourceManager.GetString("StrictByteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed struct for a decimal floating-point value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictDecimal{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[globa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictDecimalTemplate {
            get {
                return ResourceManager.GetString("StrictDecimalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed struct for a signed double-precision floating-point value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictDouble{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictDoubleTemplate {
            get {
                return ResourceManager.GetString("StrictDoubleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed struct for a signed single-precision floating point value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictFloat{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictFloatTemplate {
            get {
                return ResourceManager.GetString("StrictFloatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a Guid
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictGuid{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System.ComponentM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictGuidTemplate {
            get {
                return ResourceManager.GetString("StrictGuidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed recordstruct for a signed half-precision floating-point value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictHalf{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictHalfTemplate {
            get {
                return ResourceManager.GetString("StrictHalfTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed recordstruct for a signed 32-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictInt{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[glob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictIntTemplate {
            get {
                return ResourceManager.GetString("StrictIntTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a signed 64-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictLong{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[gl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictLongTemplate {
            get {
                return ResourceManager.GetString("StrictLongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a signed byte value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictSByte{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::Sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictSByteTemplate {
            get {
                return ResourceManager.GetString("StrictSByteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a signed 16-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictShort{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictShortTemplate {
            get {
                return ResourceManager.GetString("StrictShortTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a string value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictUString{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[global::System [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictStringTemplate {
            get {
                return ResourceManager.GetString("StrictStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a unsigned 32-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictUInt{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        ///[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictUIntTemplate {
            get {
                return ResourceManager.GetString("StrictUIntTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a unsigned 64-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictULong{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictULongTemplate {
            get {
                return ResourceManager.GetString("StrictULongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Represents a Strictly-typed record struct for a unsigned 16-bit integer value
        ////// &lt;/summary&gt;
        ////// &lt;remarks&gt;
        ////// This struct is immutable and can be used for performance-sensitive scenarios that require
        ////// type safety and minimal allocations. It implements the &lt;see cref=&quot;global::StrictlyTyped.IStrictUShort{T}&quot;/&gt; interface
        ////// for Strict typing and can be used with the &lt;see cref=&quot;global::StrictlyTyped&quot;/&gt; library.
        ////// &lt;/remarks&gt;
        ///[global::System.Diagnostics.DebuggerDisplay(&quot;{Value}&quot;)]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StrictUShortTemplate {
            get {
                return ResourceManager.GetString("StrictUShortTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StronglyTyped.StrongGuidAttribute.
        /// </summary>
        internal static string StrongGuidAttribute {
            get {
                return ResourceManager.GetString("StrongGuidAttribute", resourceCulture);
            }
        }
    }
}
